//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIBRARY_lite
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOK_LEND
    {
        public int BookLendID { get; set; }
        public int ReaderID { get; set; }
        public int InstanceSetID { get; set; }
        public System.DateTime LendDate { get; set; }
        public System.DateTime ExpReturnDate { get; set; }
        public Nullable<System.DateTime> ActReturnDate { get; set; }
        public int Prolongated { get; set; }
    
        public virtual INSTANCE_SETS INSTANCE_SETS { get; set; }
        public virtual READERS READERS { get; set; }
    }
}
