//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIBRARY_lite
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOKLEND
    {
        public int BookLendID { get; set; }
        public int ReaderID { get; set; }
        public int BookSetID { get; set; }
        public System.DateTime LendDate { get; set; }
        public System.DateTime ExpReturnDate { get; set; }
        public Nullable<System.DateTime> ActualReturnDate { get; set; }
        public int EmployeeID { get; set; }
    
        public virtual BOOK_SETS BOOK_SETS { get; set; }
        public virtual EMPLOYEES EMPLOYEES { get; set; }
        public virtual READERS READERS { get; set; }
        public string status
        {
            get
            {
                if (ActualReturnDate != null)
                {
                    return "returned";
                }
                else return "taken";
            }
        }
    }
}
