//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIBRARY_lite
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSTANCE_SET_CONTENTS
    {
        public int InstanceSetContentID { get; set; }
        public int InstanceSetID { get; set; }
        public int InstanceID { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
    
        public virtual INSTANCE_SETS INSTANCE_SETS { get; set; }
        public virtual INSTANCES INSTANCES { get; set; }
    }
}
