//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIBRARY_lite
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSTANCES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INSTANCES()
        {
            this.INSTANCE_SET_CONTENTS = new HashSet<INSTANCE_SET_CONTENTS>();
        }
    
        public int InstanceID { get; set; }
        public string ISBN { get; set; }
        public bool IsTaken { get; set; }
        public Nullable<bool> IsWorking { get; set; }
    
        public virtual BOOKS BOOKS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INSTANCE_SET_CONTENTS> INSTANCE_SET_CONTENTS { get; set; }
    }
}
