//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIBRARY_lite
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOST_BOOKS
    {
        public int LostBookID { get; set; }
        public int ReaderID { get; set; }
        public int BookID { get; set; }
        public System.DateTime LossDate { get; set; }
        public int EmployeeID { get; set; }
    
        public virtual BOOKS BOOKS { get; set; }
        public virtual EMPLOYEES EMPLOYEES { get; set; }
        public virtual READERS READERS { get; set; }
    }
}
