//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIBRARY_lite
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOKS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BOOKS()
        {
            this.INSTANCES = new HashSet<INSTANCES>();
        }
    
        public string ISBN { get; set; }
        public string BookName { get; set; }
        public int BookAuthor { get; set; }
        public int Publisher { get; set; }
        public string PublDate { get; set; }
    
        public virtual AUTHORS AUTHORS { get; set; }
        public virtual PUBLISHERS PUBLISHERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INSTANCES> INSTANCES { get; set; }
        public string author
        {
            get
            {
                return this.AUTHORS.AuthorName;
            }
        }
        public string publ
        {
            get
            {
                return this.PUBLISHERS.PublisherName;
            }
        }
    }
}
