//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIBRARY_lite
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERS
    {
        public int UserID { get; set; }
        public int EmployeeID { get; set; }
        public string ULogin { get; set; }
        public string UPassword { get; set; }
    
        public virtual EMPLOYEES EMPLOYEES { get; set; }
    }
}
