//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIBRARY_lite
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOKS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BOOKS()
        {
            this.BOOK_SET_CONTENTS = new HashSet<BOOK_SET_CONTENTS>();
            this.LOST_BOOKS = new HashSet<LOST_BOOKS>();
        }
    
        public int BookID { get; set; }
        public string ISBN { get; set; }
        public string BookName { get; set; }
        public int AuthorID { get; set; }
        public int PublisherID { get; set; }
        public int PublDate { get; set; }
        public bool IsTaken { get; set; }
        public int Quantity { get; set; }
    
        public virtual AUTHORS AUTHORS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOOK_SET_CONTENTS> BOOK_SET_CONTENTS { get; set; }
        public virtual PUBLISHERS PUBLISHERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOST_BOOKS> LOST_BOOKS { get; set; }
    }
}
