//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIBRARY_lite
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOK_SET_CONTENTS
    {
        public int BookSetContentID { get; set; }
        public int BookSetID { get; set; }
        public int BookID { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
    
        public virtual BOOKS BOOKS { get; set; }
        public virtual BOOK_SETS BOOK_SETS { get; set; }
    }
}
