//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIBRARY_lite
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEES
    {
        public int EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public int RoleID { get; set; }
        public bool IsWorking { get; set; }
        public string ELogin { get; set; }
        public string EPassword { get; set; }
    
        public virtual ROLES ROLES { get; set; }
    }
}
